server:
  port: 8090
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: mysecretpassword
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      idle-timeout: 60000
      minimum-idle: 2
  jpa:
    properties:
       hibernate:
         jdbc:
           lob:
             non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
